language: scala
sudo: false

scala:
  - 2.13.1
  - 2.12.10

jdk:
  - openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
