addSbtPlugin("org.scala-js"       % "sbt-scalajs"          % "0.6.13")
addSbtPlugin("com.typesafe.sbt"   % "sbt-pgp"              % "0.8.3")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"          % "0.3.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"              % "0.2.18")
